model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

model_teacher: 
  name: resnet50
  kwargs: {}
  last_layer: [2048, 7]

dataset: 
  name: PACS_dataset
  kwargs: 
    domain_list: ["art_painting", "photo", "sketch", "cartoon"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 227
  - name: RandomHorizontalFlip
    kwargs: {}
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
mixup: null
optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: 500
tracking_step: 50
batch_size: 64
seed: 1
temperature: 5

swad: null

run_id: augs_distillation_baseline
run_id_teacher: augs_teacher_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
