model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V2
  last_layer: [512, 7]

model_teacher: 
  name: resnet34
  kwargs: {}
  last_layer: [512, 7]

dataset: 
  name: PACS_dataset
  kwargs: 
    domain_list: ["art_painting", "photo", "sketch", "cartoon"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 227
  - name: RandomHorizontalFlip
    kwargs: {}
  - name: ColorJitter
    kwargs: 
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.3
  - name: RandomGrayscale
    kwargs: {}
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
mixup: 0.2
optimizer:
  name: SGD
  kwargs:
    lr: 0.003
    momentum: 0.9
scheduler:
  name: CosineAnnealingLR
  kwargs:
    eta_min: 0.00003
    T_max: 500
num_epochs: 500
tracking_step: 50
batch_size: 64
seed: 2023
temperature: 5

swad: null

run_id: augs_distillation_domainbed_and_mixup
run_id_teacher: augs_teacher_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
