model: 
  name: resnet50
  kwargs:
    weights: ResNet50_Weights.IMAGENET1K_V2
  last_layer: [2048, 7]

dataset: 
  name: PACS
  kwargs: 
    domain_list: ["art_painting", "photo", "sketch", "cartoon"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 224
      scale: [0.7, 1.0]
  - name: RandomHorizontalFlip
    kwargs: {}
transforms:
  - name: Resize
    kwargs:
      size: [224, 224]
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: 100
tracking_step: 10
batch_size: 64
seed: 1

swad: null

run_id: augs_teacher_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
