model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

dataset: 
  name: VLCS
  kwargs: 
    domain_list: ["Caltech101", "LabelMe", "SUN09", "VOC2007"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 227
      scale: [0.8, 1.0]
      ratio: [0.9, 1.1]
  - name: RandomHorizontalFlip
    kwargs: {}
  - name: ColorJitter
    kwargs: 
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.3
  - name: RandomGrayscale
    kwargs: {}
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: null
tracking_step: 500
batch_size: 64
seed: 1

swad:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 1.3
  num_iterations: 5000
  frequency: 100
  our_swad_begin: null

run_id: vlcs_swad_student_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
