model: 
  name: facebook/deit-tiny-distilled-patch16-224
  num_labels: 65

dataset: 
  name: OfficeHome
  kwargs: 
    domain_list: ["Art", "Clipart", "Product", "Real_World"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 224
      scale: [0.7, 1.0]
  - name: RandomHorizontalFlip
    kwargs: {}
  - name: ColorJitter
    kwargs: 
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.3
  - name: RandomGrayscale
    kwargs: {}
transforms:
  - name: Resize
    kwargs:
      size: [224, 224]
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: null
tracking_step: 500
batch_size: 64
seed: 2

swad:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 1.3
  num_iterations: 5000
  frequency: 100
  our_swad_begin: null

run_id: officehome_deit_student_baseline_2

wandb_project: dist-gen
wandb_entity: gegelyanec
