model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

model_teacher: 
  name: resnet50
  kwargs: {}
  last_layer: [2048, 7]

dataset: 
  name: VLCS
  kwargs: 
    domain_list: ["Caltech101", "LabelMe", "SUN09", "VOC2007"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 227
  - name: RandomHorizontalFlip
    kwargs: {}
  - name: ColorJitter
    kwargs: 
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.3
  - name: RandomGrayscale
    kwargs: {}
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
mixup: null
optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: 500
tracking_step: 50
batch_size: 64
seed: 1
temperature: 5
image_net: false

swad: null

run_id: vlcs_augs_distillation_domainbed
run_id_teacher: vlcs_augs_teacher_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
