model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

dataset: 
  name: VLCS
  kwargs: 
    domain_list: ["Caltech101", "LabelMe", "SUN09", "VOC2007"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 224
      scale: [0.7, 1.0]
  - name: RandomHorizontalFlip
    kwargs: {}
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: 500
tracking_step: 50
batch_size: 64
seed: 1

swad: null

run_id: vlcs_augs_student_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
