model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

model_teacher: 
  name: resnet50
  kwargs: {}
  last_layer: [2048, 7]

dataset: 
  name: PACS_dataset
  kwargs: 
    domain_list: ["art_painting", "photo", "sketch", "cartoon"]
augmentations:
  - name: RandomResizedCrop
    kwargs: 
      size: 227
  - name: RandomHorizontalFlip
    kwargs: {}
  - name: ColorJitter
    kwargs: 
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.3
  - name: RandomGrayscale
    kwargs: {}
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
mixup: null
optimizer:
  name: Adam
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: null
tracking_step: 5000
batch_size: 64
seed: 2023
temperature: 5

swad:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 1.3
  num_iterations: 50000
  frequency: 100
  our_swad_begin: 10000

run_id: swad_distillation_baseline
run_id_teacher: swad_teacher_baseline

wandb_project: dist-gen
wandb_entity: gegelyanec
